<#
.SYNOPSIS
  Scans the AutoApiEngine codebase and updates agent reference caches.
.PARAMETER UpdateRefs
  If set, also regenerates FE_REFERENCE.md and BE_REFERENCE.md from scan data.
#>

param([switch]$UpdateRefs)

$root = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$scanDir = Join-Path $root ".opencode\agents\.scan"
if (-not (Test-Path $scanDir)) { New-Item -ItemType Directory -Path $scanDir -Force | Out-Null }

Write-Host "=== AutoApiEngine Agent Sync ===" -ForegroundColor Cyan

# ─── SCAN FE ────────────────────────────────
Write-Host "[FE] Scanning routes..." -ForegroundColor Yellow
$routes = @()
$routeText = Get-Content (Join-Path $root "FE\src\app\app.routes.ts") -Raw
$pat = [regex]::new("path:\s*'([^']+)'(?:,\s*canActivate:\s*\[(\w+Guard)\])?.*?loadComponent:\s*\(\)\s*=>\s*import\('([^']+)'\)", 'Singleline')
foreach ($m in $pat.Matches($routeText)) {
    $routes += [ordered]@{ path = $m.Groups[1].Value; guard = if ($m.Groups[2].Success) { $m.Groups[2].Value } else { $null }; module = $m.Groups[3].Value }
}
$envCfg = [ordered]@{}
foreach ($line in (Get-Content (Join-Path $root "FE\src\environments\environment.ts"))) {
    if ($line -match "^\s+(\w+):\s*'([^']+)'") { $envCfg[$matches[1]] = $matches[2] }
}
Write-Host "  $($routes.Count) routes"

# ─── SCAN BE ────────────────────────────────
Write-Host "[BE] Scanning controllers..." -ForegroundColor Yellow
$controllers = [ordered]@{}
Get-ChildItem (Join-Path $root "BE") -Recurse -Filter "*Controller.cs" | Where-Object { $_.FullName -notmatch "\\bin\\|\\obj\\" } | ForEach-Object {
    $ctrlName = ""; $ctrlRoute = ""; $endpoints = @()
    foreach ($line in (Get-Content $_.FullName)) {
        $t = $line.Trim()
        if ($t -match "class\s+(\w+Controller)") { $ctrlName = $matches[1]; continue }
        if ($t -match '\[Route\("([^"]+)"\)\]') { $ctrlRoute = $matches[1]; continue }
        if ($t -match '\[Http(\w+)\(\"([^"]*)\"\)\]') {
            $epRoute = $matches[2]
            $full = if ($ctrlRoute) { "/$ctrlRoute/$epRoute" -replace '/+$','' } else { "/$epRoute" }
            $endpoints += [ordered]@{ method = $matches[1]; route = $full }
            continue
        }
        if ($t -match '\[Http(\w+)\]') {
            $full = if ($ctrlRoute) { "/$ctrlRoute" } else { "/" }
            $endpoints += [ordered]@{ method = $matches[1]; route = $full }
        }
    }
    if ($ctrlName) { $controllers[$ctrlName] = [ordered]@{ route = $ctrlRoute; endpoints = $endpoints } }
}
Write-Host "  $($controllers.Count) controllers"

# ─── SCAN DOCKER ────────────────────────────
Write-Host "[Docker] Scanning compose..." -ForegroundColor Yellow
$services = @()
foreach ($line in (Get-Content (Join-Path $root "DockerImages\docker-compose.yml"))) {
    if ($line -match "^\s{2}(\w+):\s*$" -and $line -notmatch "services:|volumes:|networks:") { $services += $matches[1] }
}
Write-Host "  $($services.Count) services"

# ─── WRITE CACHE ────────────────────────────
Write-Host "[Cache] Writing..." -ForegroundColor Yellow
[ordered]@{ scannedAt = (Get-Date -Format "yyyy-MM-dd HH:mm:ss"); routes = $routes; env = $envCfg } |
    ConvertTo-Json -Depth 5 | Set-Content (Join-Path $scanDir "fe-routes.json") -Encoding UTF8
[ordered]@{ scannedAt = (Get-Date -Format "yyyy-MM-dd HH:mm:ss"); controllers = $controllers } |
    ConvertTo-Json -Depth 5 | Set-Content (Join-Path $scanDir "be-endpoints.json") -Encoding UTF8
[ordered]@{ scannedAt = (Get-Date -Format "yyyy-MM-dd HH:mm:ss"); services = $services } |
    ConvertTo-Json -Depth 3 | Set-Content (Join-Path $scanDir "docker-services.json") -Encoding UTF8
Write-Host "[Cache] Done" -ForegroundColor Green

# ─── REGENERATE REFS ────────────────────────
if ($UpdateRefs) {
    Write-Host "[Refs] Regenerating FE_REFERENCE.md..." -ForegroundColor Yellow
    $feRef = "# AutoApiEngine Frontend Reference`n*Generated by tools/sync-agents.ps1 at $((Get-Date -Format 'yyyy-MM-dd HH:mm'))*`n`n## Routes`n`n| Path | Guard | Module |`n|------|-------|--------|`n"
    foreach ($r in $routes) {
        $g = if ($r.guard) { $r.guard } else { "—" }
        $feRef += "| /$($r.path) | $g | $($r.module) |`n"
    }
    $feRef += "`n## Environment`n`n| Key | Value |`n|-----|-------|`n"
    foreach ($kv in $envCfg.GetEnumerator()) { $feRef += "| $($kv.Key) | $($kv.Value) |`n" }
    $feRef | Set-Content (Join-Path $root "FE_REFERENCE.md") -Encoding UTF8

    Write-Host "[Refs] Regenerating BE_REFERENCE.md..." -ForegroundColor Yellow
    $beRef = "# AutoApiEngine Backend Reference`n*Generated by tools/sync-agents.ps1 at $((Get-Date -Format 'yyyy-MM-dd HH:mm'))*`n`n## Controllers`n`n"
    foreach ($kv in $controllers.GetEnumerator()) {
        $beRef += "### $($kv.Key) (/$($kv.Value.route))`n`n| Method | Route |`n|--------|-------|`n"
        foreach ($ep in $kv.Value.endpoints) { $beRef += "| $($ep.method) | $($ep.route) |`n" }
        $beRef += "`n"
    }
    $beRef | Set-Content (Join-Path $root "BE_REFERENCE.md") -Encoding UTF8
    Write-Host "[Refs] Done" -ForegroundColor Green
}

Write-Host "=== Sync complete ===" -ForegroundColor Cyan
