<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AutoApiEngine.Domain\AutoApiEngine.Domain.csproj" />
    <ProjectReference Include="..\AutoApiEngine.Persistence\AutoApiEngine.Persistence.csproj" />
    <ProjectReference Include="..\AutoApiEngine.ServiceAbstraction\AutoApiEngine.ServiceAbstraction.csproj" />
    <ProjectReference Include="..\AutoApiEngine.Services\AutoApiEngine.Services.csproj" />
  </ItemGroup>
</Project>
